[package]
name = "sabiptrace"
version = "0.1.0"
authors = ["Kazuhiro Kobayashi <orihuzakihsayabok@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
log = "0.4"
nalgebra = "0.17.0"
num_cpus = "1.10"
openexr = "0.6.0"
rand = "0.6"
half = "1.3"
getopts = "0.2"
